// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sumevents_c
List sumevents_c(int i, arma::mat X, arma::mat Ftime, arma::mat theta, int n, int p, arma::vec eventtimes);
RcppExport SEXP _ProxCox_sumevents_c(SEXP iSEXP, SEXP XSEXP, SEXP FtimeSEXP, SEXP thetaSEXP, SEXP nSEXP, SEXP pSEXP, SEXP eventtimesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ftime(FtimeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eventtimes(eventtimesSEXP);
    rcpp_result_gen = Rcpp::wrap(sumevents_c(i, X, Ftime, theta, n, p, eventtimes));
    return rcpp_result_gen;
END_RCPP
}
// timesTwo
int timesTwo(int x);
RcppExport SEXP _ProxCox_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ProxCox_sumevents_c", (DL_FUNC) &_ProxCox_sumevents_c, 7},
    {"_ProxCox_timesTwo", (DL_FUNC) &_ProxCox_timesTwo, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ProxCox(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
