# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' helper function written in Rcpp/RcppArmadilllo
#' @param i current index
#' @param X feature matrix
#' @param Ftime matrix of values of the basis for certain time points
#' @param theta current parameters of partial Cox likelihood
#' @param n dimension
#' @param p number of variables
#' @param eventtimes indexes of individuals that had event of interest
NULL

sumevents_c <- function(i, X, Ftime, theta, n, p, eventtimes) {
    .Call(`_ProxCox_sumevents_c`, i, X, Ftime, theta, n, p, eventtimes)
}

timesTwo <- function(x) {
    .Call(`_ProxCox_timesTwo`, x)
}

